server:
  port: 7070
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://todo-db.cnnjgknypryq.ap-south-1.rds.amazonaws.com:3306/tododb
    username: admin
    password: admin123
  jpa:
    hibernate.ddl-auto: validate
    generate-ddl: true
    show-sql: true
keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: todo-realm
  resource: todo-service
  bearer-only: true
  ssl-required: external
  credentials:
    secret : 850fb83a-54d0-41eb-aa46-d1de6c7b3d11
  public-client: true
  principal-attribute: preferred_username
  use-resource-role-mappings: true    